kartoza/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('map_routing.urls')),
]

map_routing/urls.py
"""Url paths implementations for map routing app."""
from django.urls import path

from . import views
app_name = 'map_routing'

urlpatterns = [
    path('', views.render_route, name='render_route'),
    path('upload/', views.upload_geopackage, name='upload_geopackage'),
    path('save/', views.export_to_gpkg_file, name='export_to_gpkg_file')
]

core/models.py
"""Custom user model implemetation to use an email as a username."""
from typing import Any
from typing import Union

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    """Create custom user manager for email addresses as the username."""

    def create_user(self, email: str,
                    password: Union[None, str] = None, **extra_fields: Any) -> Any:
        """
        Create a new user object.

        :param email: The email address of the user
        :param password: If a password is provided, it will be hashed and set on the user
        :return: A user instance
        """
        if not email:
            raise ValueError('User must have an email address.')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        """Create a Django super user."""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Implement a user model to support email addresses as a username."""

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'email'

map_routing/models.py
"""Django Data models."""
from django.contrib.gis.db import models


class SpikeyPolygon(models.Model):
    """Database model implementation for SpikeyPolygons data."""

    file_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    geometry = models.PolygonField(blank=True, null=True)

    @classmethod
    def create(cls, file_id, name=None, geometry=None):
        """Create a SpikeyPolygon Model instance."""
        book = cls(file_id=file_id, name=name, geometry=geometry)
        return book

map_routing/views.py
"""Implementation of django views."""
import json
from typing import Any
from typing import List
from typing import Set
from typing import Tuple
from typing import Union

import geopandas
from django.http import FileResponse
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from environs import Env

from .filters import PolySpikeFilter
from .models import SpikeyPolygon
# Environs Config
env = Env()
env.read_env()


def chunks(lst: Union[List, Tuple, Set], n: int) -> Union[List, Tuple, Set]:
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]


def apply_rdp_to_polygon(poly, tolerance: float = 0.0000000001,
                         preserve_topology: bool = True) -> Any:
    """Reduce data point using RammerDouglasPecker."""
    return(poly.geometry.simplify(tolerance=tolerance,
                                  preserve_topology=preserve_topology))


def get_polygons():
    """
    Get Polygons from Database and split them in to a lost of coordinates.

    :return: A list of lists of lists of tuples.
    """
    pollies = SpikeyPolygon.objects.all()
    polygons = list()
    for poly in pollies:
        polygons.append(dict(file_id=poly.file_id, name=poly.name,
                        coords=poly.geometry.coords))

    return polygons


@require_http_methods(['GET'])
def render_route(request):
    """Display polygons on map."""
    pollies = get_polygons()
    filtered_polygons = []
    for poly in pollies:
        filtered_polygons.append(
            dict(data=PolySpikeFilter(poly).filtered_poly,
                 file_id=poly['file_id'],
                 name=poly['name']))

    polygons = filtered_polygons if filtered_polygons else {}

    return render(request, 'improved_map.html',
                  dict(polygons=json.dumps(polygons),
                       map_center=PolySpikeFilter.MAP_CENTER))


@require_http_methods(['POST'])
def upload_geopackage(request) -> HttpResponse:
    """Ingest a geopackage file."""
    for filename, file in request.FILES.items():
        output_filename = f'uploaded_{request.FILES[filename]}'
        with open(output_filename, 'wb') as fin:
            fin.write(request.FILES[filename].read())

        gdf = geopandas.read_file(output_filename)
        json_data = json.loads(gdf.to_json())
        for entry in json_data['features']:
            data = {
                'file_id': entry['id'],
                'name': entry.get('properties', '').get('name', ''),
                'geometry': json.dumps(entry.get('geometry', dict()))
            }
            SpikeyPolygon(**data).save()

    return redirect('/')


@require_http_methods('POST')
def export_to_gpkg_file(request):
    """Export a polygon to a geopackage file."""
    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)

    coordinates = []
    for coord in body['geometry']['coordinates']:
        coordinates.append([coord['lat'], coord['lng']])
    body['geometry']['coordinates'] = [coordinates, ]
    new_geojson = dict(
        type='FeatureCollection',
        features=[
            dict(
                id=body['file_id'],
                type='Feature',
                properties=dict(name=body['name']),
                geometry=body['geometry'],
            )])
    gdf = geopandas.GeoDataFrame.from_features(new_geojson['features'])
    gdf.to_file('dataframe.gpkg', driver='GPKG')
    return FileResponse(open('dataframe.gpkg', 'rb'))

map_routing/templates/improved_map.html
<html>
   <title>Kartoza</title>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
   <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
   <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100%; width: 100%;}
      /* Style the navbar */
      #navbar {
      overflow: hidden;
      background-color: #333;
      }
      /* Navbar links */
      #navbar a {
      float: left;
      display: block;
      color: #f2f2f2;
      text-align: center;
      padding: 14px;
      text-decoration: none;
      }
   </style>
   <body>
      <div id="navbar">
         <a href="#home">Home</a>
         <a onClick="openFile();">Open</a>
         <a onClick="saveFile();">Save</a>
      </div>
      <div id="map_canvas"></div>
      <div class="ui basic modal upload">
         <div class="ui icon header">
            <i class="map icon"></i>
            Upload A GeoPackage File
         </div>
         <div class="content ">
            <div class="ui equal width center aligned padded grid">
               <form class="ui form" action="{% url 'map_routing:upload_geopackage' %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="field">
                     <input type="file" name="file" placeholder="Select a file">
                  </div>
                  <div class="actions">
                     <div class="ui red basic cancel inverted button">
                        <i class="remove icon"></i>
                        Cancel
                     </div>
                     <button class="ui green ok inverted button" type="submit">Upload</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
      <div class="ui basic modal save">
         <div class="ui icon header">
            <i class="file alternate icon"></i>
            Export Polygon To File.
         </div>
         <div class="content ">
            <div class="ui equal width center aligned padded grid">
               <form class="ui form" onsubmit="return exportFile();">
                  {% csrf_token %}
                  <div class="field">
                     <input type="text" name="file-name" placeholder="Please enter a file name.">
                  </div>
                  <div class="actions">
                     <div class="ui red basic cancel inverted button">
                        <i class="remove icon"></i>
                        Cancel
                     </div>
                     <button class="ui green ok inverted button" type="submit">Export</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
      <body>
         <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js"></script>
         <script>
            var selected_poly = null;
            const polygons = {{ polygons | safe }}
            const openFile = () => {
                $('.ui.basic.modal.upload').modal('show');
            }

            const saveFile = () => {
                $('.ui.basic.modal.save').modal('show');
            }

            const getCookie = (name) => {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            const downloadFileResponse = (res) => {
                try {
                    res.blob().then((data) => {
                    const newBlob = new Blob([data]);

                    const blobUrl = window.URL.createObjectURL(newBlob);

                    const link = document.createElement('a');
                    link.href = blobUrl;
                    link.setAttribute('download', `geopackage.gpkg`);
                    document.body.appendChild(link);
                    link.click();
                    link.parentNode.removeChild(link);

                    // clean up Url
                    window.URL.revokeObjectURL(blobUrl);
                    }).catch(err => console.error(err));
                } catch (exc) {
                    console.log("Save Blob method failed with the following exception.");
                    console.log(exc);
                }
            }

            const exportFile = () => {
                const data = {
                    file_id: selected_poly.file_id,
                    name: selected_poly.name,
                    geometry: {
                        type: "Polygon",
                        coordinates: selected_poly.data.coordinates
                    }
                }
                fetch("{% url 'map_routing:export_to_gpkg_file' %}", {
                    method: "POST",
                    body: JSON.stringify(data),
                    credentials: 'same-origin',
                    headers: {
                        "X-CSRFToken": getCookie("csrftoken")
                    }
                }).then(res => {
                    downloadFileResponse(res);
                    $('.ui.basic.modal.save').modal('hide');
                });
                return false;
            }




            class KartozaPolygon{
            constructor(polygon, map){

                this.map = map
                this.fileId = polygon.file_id
                this.name = polygon.name
                this.polygon = polygon.data;
                this.coordinates = new Array();
                this.polylines = new Array();
                this.createCoordinates();
                this.createPolylines()


                this.addOnClickListener(this)
            }


            createCoordinates(){
                this.polygon.forEach((coord) => {
                    this.coordinates.push(new google.maps.LatLng(coord[0], coord[1]));
                });
            }

            createPolylines(){
                this.polylines = new google.maps.Polyline({
                path: this.coordinates,
                strokeColor: '#'+Math.floor(Math.random()*16777215).toString(16),
                strokeOpacity: 1.0,
                strokeWeight: 4,
                geodesic: true,
                map: this.map
            });
            }


            addOnClickListener(self){
                google.maps.event.addListener(this.polylines, 'click', function (event, fileId) {
                    selected_poly = { data: self, file_id: self.fileId, name: self.name};
                    $('.ui.basic.modal.save').modal('show');
                });
            }
            }

            const initialize = (() => {
                {% if map_center %}
                    var homeLatlng = new google.maps.LatLng{{ map_center }};
                    var mapZoom = 8
                {% else %}
                    var homeLatlng = new google.maps.LatLng(0,0)
                    var mapZoom = 4
                {% endif %}
                var myOptions = {
                    zoom: mapZoom,
                    center: homeLatlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

            const pollies = new Array();

            for (poly in polygons){
                pollies.push(new KartozaPolygon( polygons[poly] , map));
            }


            });

            google.maps.event.addDomListener(window, 'load', initialize);


         </script>
</html>